# Generated by Django 5.0.6 on 2024-07-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carmodel_engine'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.usermodel'),
            preserve_default=False,
        ),
    ]
