# Generated by Django 5.0.6 on 2024-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_age_remove_usermodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_bayer',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
