# Generated by Django 5.0.6 on 2024-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_options_alter_carmodel_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo_car',
            field=models.ImageField(default=1, upload_to='photo_car'),
            preserve_default=False,
        ),
    ]
